---
- name: Include tasks for pre-setup checks
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: Include tasks to form urls
  ansible.builtin.include_tasks:
    file: caddy-url.yml

- name: Create group
  ansible.builtin.group:
    name: "{{ install_caddy_user }}"
    system: true
    state: present

- name: Create Caddy user
  ansible.builtin.user:
    name: "{{ install_caddy_user }}"
    system: true
    create_home: true
    home: "{{ install_caddy_home }}"
    group: "{{ install_caddy_user }}"
    state: present
  register: __caddy_user

- name: Get current Caddy version # noqa: risky-shell-pipe
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/caddy -v | cut -d " " -f 1
  changed_when: false
  failed_when: false
  register: __caddy_version

- name: Download Caddy
  when: __caddy_version.stdout != install_caddy_version or install_caddy_force_update
  ansible.builtin.get_url:
    url: "{{ caddy_download_url }}"
    checksum: "{{ caddy_checksum_url | default(omit) }}"
    dest: "{{ install_caddy_home }}/caddy.tar.gz"
    force: true
    mode: "0644"
    owner: "{{ install_caddy_user }}"
    group: "{{ __caddy_user.group }}"
  retries: 3
  delay: 2
  register: __caddy_download
  notify: Extract Caddy

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ install_caddy_user }}"
    mode: "0750"
  loop:
    - /etc/caddy
    - /var/lib/caddy
    - /var/log/caddy

- name: Set capability on caddy binary to use port < 1024 # noqa: no-handler
  when: __caddy_download.changed
  community.general.capabilities:
    path: "/usr/local/bin/caddy"
    capability: cap_net_bind_service+eip
    state: present

- name: Create caddy config
  ansible.builtin.copy:
    content: "{{ install_caddy_caddyfile }}"
    dest: /etc/caddy/Caddyfile
    owner: "{{ install_caddy_user }}"
    group: "{{ __caddy_user.group }}"
    mode: "0640"
  notify: Reload caddy

- name: Template systemd service
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart caddy

- name: Start Caddy service
  ansible.builtin.systemd_service:
    name: caddy
    state: started
    enabled: true
    daemon_reload: true
